spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ttms?serverTimezone=Asia/Shanghai
    username: root
    password: root
#配置mybatis的相关配置
mybatis:
  configuration:
    map-underscore-to-camel-case: true
